# Generated by Django 5.2.1 on 2025-05-29 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenseUI", "0003_alter_addincomemodel_category_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AddExpenseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Expense", models.PositiveIntegerField()),
                (
                    "Payment_Method",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("upi", "UPI"),
                            ("other income", "Other Income"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "Category",
                    models.CharField(
                        choices=[
                            ("health", "Health"),
                            ("shopping", "Shopping"),
                            ("salary", "Salary"),
                            ("food", "Food"),
                            ("entertainment", "Entertainment"),
                            ("other income", "Other Income"),
                        ],
                        max_length=20,
                    ),
                ),
                ("Notes", models.CharField(blank=True, max_length=200, null=True)),
                ("Date", models.DateField()),
                ("Time", models.TimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
